# Configuration to minimize binary size

[profile.release]
debug = true
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "immediate-abort"
rustflags = ["-Zlocation-detail=none"]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["optimize_for_size"]
panic-immediate-abort = true
