cargo-features = ["per-package-target"]

[package]
name = "keyball61-nrf"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
# tombi: lint.rules.key-not-allowed.disabled = true
forced-target = "thumbv7em-none-eabihf"

[lib]
bench = false
doctest = false
path = "src/lib.rs"
test = false

[[bin]]
bench = false
doctest = false
name = "keyball61"
test = false

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
embassy-embedded-hal = { workspace = true }
embassy-executor = { workspace = true, features = [
  "arch-cortex-m",
  "executor-interrupt",
  "executor-thread",
] }
embassy-nrf = { workspace = true, features = [
  "gpiote",
  "nfc-pins-as-gpio",
  "nrf52840",
  "time-driver-rtc1",
  "unstable-pac",
] }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }
keyball61-common = { path = "../keyball61-common/" }
nrf-softdevice = { workspace = true, features = [
  "ble-central",
  "ble-peripheral",
  "critical-section-impl",
  "nrf52840",
  "s140",
] }
rktk = { workspace = true }
rktk-drivers-common = { workspace = true }
rktk-drivers-nrf = { workspace = true }

[features]
default = ["ble", "usb"]
_check = []
ble = ["rktk-drivers-nrf/softdevice-ble"]
usb = ["rktk-drivers-nrf/softdevice"]
