[package]
name = "keyball61-common"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
rktk = { workspace = true }
rktk-drivers-common = { workspace = true }

[features]
_check = []
