[package]
name = "keyball61-rp"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
bench = false
doctest = false
path = "src/lib.rs"
test = false

[[bin]]
bench = false
doctest = false
name = "keyball61"
test = false

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
defmt = { workspace = true, optional = true }
embassy-embedded-hal = { workspace = true }
embassy-executor = { workspace = true, features = [
  "arch-cortex-m",
  "executor-interrupt",
  "executor-thread",
] }
embassy-rp = { workspace = true, features = [
  "critical-section-impl",
  "rp2040",
  "time-driver",
] }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }
keyball61-common = { path = "../keyball61-common/" }
portable-atomic = { version = "1.6.0", features = [
  "unsafe-assume-single-core",
] }
rktk = { workspace = true, features = ["rrp"] }
rktk-drivers-common = { workspace = true }
rktk-drivers-rp = { workspace = true }

[features]
default = ["defmt"]
_check = []
defmt = [
  "dep:defmt",
  "rktk-drivers-common/defmt-timestamp",
  "rktk-drivers-common/defmt-usb",
  "rktk-drivers-rp/defmt",
  "rktk/defmt",
]
