# You can remove this line and `forced-target` property and use `.cargo/config.toml` if your crate isn't in workspace.
cargo-features = ["panic-immediate-abort"]

[[bin]]
name = "corne-nrf"
path = "src/main.rs"
test = false
doctest = false
bench = false

[package]
name = "corne-nrf"
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[dependencies]
rktk = { workspace = true }
rktk-drivers-nrf = { workspace = true, features = ["softdevice-ble"] }
rktk-drivers-common = { workspace = true }

cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
embassy-executor = { workspace = true, features = [
  "arch-cortex-m",
  "executor-thread",
  "executor-interrupt",
] }

embassy-nrf = { workspace = true, features = [
  "gpiote",
  "time-driver-rtc1",
  "nrf52840",
  "nfc-pins-as-gpio",
] }
nrf-softdevice = { workspace = true, features = [
  "critical-section-impl",
  "s140",
  "nrf52840",
] }

[features]
default = ["right"]

right = []
left = []

# Remove this line in your project. It's just used in this workspace for check.
_check = []
